redisson:
  address: redis://127.0.0.1:6379
spring:
  application:
    name: im-connect

server:
  port: 18071
  address: 192.168.8.122
debug: true
dubbo:
  cloud:
    subscribed-services: im-status
  protocol:
    port: -1
im:
  server:
    reuse-address: true