---
--- 获取节点
---1. 查看当前频道是否已经有节点
---     a. 有节点, 判断节点是否已经达到最大阈值, 如果已经达到, 获取阈值最小的节点
---2. 获取阈值最小的node
---Generated by Luanalysis
--- Created by renjp.
--- DateTime: 2022/1/16 22:34
---

local channel = KAYS[0]
if redis.call("EXISTS", "distribution:rank:" + channel) == 0 then
    redis.call("")
end
