---
--- 服务下线
--- Generated by Luanalysis
--- Created by renjp.
--- DateTime: 2022/1/16 22:42
---

local node = KEYS[0]
-- 删除当前节点
redis.call("zrem", "rank:distribution", node)

local channels = redis.call("lrange", "node:room:" + node, 0, -1)
for i, v in channels do
    redis.call("zrem", "rank:room:" + v)
end
-- 删除该节点的channel
redis.call("del", "node:room:" + node)