---
--- 服务上线
--- 1. 删除当前节点
--- 2. 从room 中移除当前节点
--- Generated by Luanalysis
--- Created by renjp.
--- DateTime: 2022/1/16 22:41
---

local server = KEYS[0]

redis.call("zadd", "distribution:rank", 0, server)
